### ISSUE TITLE
Feature request: Specify custom `console`

### ISSUE THREAD

**Issue by leethree** [blackxored/apollo-link-logger#1]
I'm trying to use `apollo-link-logger` in React Native and it turns out `group` and `groupEnd` are not supported by the default global `console` in React Native. We would like to use our own custom `console` implementation but there's no way to do that without polluting the globals.

![simulator screen shot - iphone 6 - 2017-12-05 at 11 27 46](https://user-images.githubusercontent.com/648142/33589096-84dba8be-d9b1-11e7-849e-43bae07c6dfd.png)

It would be very useful for `apollo-link-logger` to support custom `console` objects. Thanks!

**Comment by blackxored** [comment]
Are you getting any errors? AFAIK both are supported.

**Comment by leethree** [comment]
React-native has a "Debug JS Remotely" mode where Chrome is used as JS runtime, which supports `console.group`/`groupEnd`. But when debugging mode is off, it uses JavaScriptCore, which doesn't support `console.group`. 

See: [JavaScript Environment · React Native](https://facebook.github.io/react-native/docs/javascript-environment#javascript-runtime)

For example, 

```js
console.group('test');
```

will result in:

![simulator screen shot - iphone 6 - 2017-12-05 at 11 42 43](https://user-images.githubusercontent.com/648142/33589081-78067d3a-d9b1-11e7-8b98-6ac09b42f8c8.png)

I also added the screenshot to the original comment.

**Comment by adambom** [comment]
I can confirm this is a problem in version 1.0.4. When debugging mode is turned off, using this link results in a network error that can be traced back to [this console.groupCollapsed](https://github.com/blackxored/apollo-link-logger/blob/c77b2c72f8d5eb13208c278fe6dae4fab3aca882/src/index.js#L13) call.

**Comment by blackxored** [comment]
Thanks. I’ll take a look this Saturday.

-- 
Best Regards,

Adrian Perez
https://adrianperez.codes

**Comment by adambom** [comment]
@blackxored Take a look at #3. Should fix the problem.
