### ISSUE TITLE
subscription should not print ellapsed color code.

### ISSUE THREAD

**Issue by cncolder** [blackxored/apollo-link-logger#29]
* `apollo-link-logger` version: 1.2.2
* `node` version: 10.6.0
* `npm` (or `yarn`) version: 1.7.0
* `chrome` version: 67.0.3396.99

Relevant code or config

```javascript
if (dev) {
    links.unshift(apolloLogger)
}
```

What you did:

What happened:

![2018-07-18 20 23 44](https://user-images.githubusercontent.com/127009/42881590-3dd1dcd4-8aca-11e8-862d-abc82d2cb1bf.png)

Reproduction repository:

Problem description:

Suggested solution:

**Comment by maxieblake** [comment]
Same issue.
There is open PR #27 with fix.
@blackxored can you review it?

**Comment by blackxored** [comment]
I merged it. Please confirm this is fixed in 1.2.3.
