### ISSUE TITLE
Invalid assignment error in production webpack build

### ISSUE THREAD

**Issue by samcorcos** [blackxored/apollo-link-logger#4]
* `apollo-link-logger` version: 1.0.4
* `node` version: 8.8.1
* `npm` (or `yarn`) version: 5.5.1

Relevant code or config

```javascript
export const client = new ApolloClient({
  link: from([
    apolloLogger,
    setAuthorizationMiddlewareLink,
    link,
  ]),
  cache: new InMemoryCache(),
})
```

What happened:

Everything works fine in development, but the production webpack build fails with the following message:

```
ERROR in bundle.js from UglifyJs
Invalid assignment [/Users/xxxx/code/cardash/~/apollo-link-logger/src/formatMessage.js:1,0][bundle.js:102988,59]
```

Problem description:

The logger works great in development (`webpack`) but fails on production build (`webpack -p`)

Suggested solution:

I'm not entirely sure, since the node version I'm running appears to support the operation in `formatMessage`.

**Comment by blackxored** [comment]
Can you test this again with 1.1.0?

**Comment by samcorcos** [comment]
That appears to have solved the problem. Thank you.

**Comment by blackxored** [comment]
Glad to hear that! I'd personally recommend to not include middleware like this in production (think redux-logger, where in most cases you'd want to exclude that from prod), but I'm happy this solved it for your case.
