### ISSUE TITLE
Transpile version of the package

### ISSUE THREAD

**Issue by idanwe** [blackxored/apollo-link-logger#5]
* `apollo-link-logger` version: latest
* `node` version: 8.9.3
* `npm` (or `yarn`) version: 5.5.1

Relevant code or config

```javascript
const { ApolloLink } = require('apollo-link'); 
... and the rest of the file :)
```

I'm using the package as part of a meteor project and the node_modules are not transpile as part of the build process.
Is it possible to publish some kind of dist file?

thanks for the help

**Comment by blackxored** [comment]
Thanks for pointing this out, will resolve shortly.
