### ISSUE TITLE
Query Name Color Conflicts with the Chrome console Dark Theme

### ISSUE THREAD

**Issue by romarioraffington** [blackxored/apollo-link-logger#6]
* `apollo-link-logger` version: 1.1.0
* `node` version: 6.11.5
* `npm` (or `yarn`) version: 1.3.2

<img width="315" alt="screen shot 2018-01-16 at 1 39 08 pm" src="https://user-images.githubusercontent.com/7076981/35005845-d1b7e418-fac2-11e7-8a3a-b8c115be3d4d.png">

Is it possible to change the query name to a lighter text?  Since the query text is black it conflicts when the chrome console is using the dark theme

Problem description: Query name color conflicts with the chrome console dark theme

Suggested solution: Change the query name color to a lighter text

**Comment by romarioraffington** [comment]
Thoughts @blackxored? I'm willing to submit a PR for this... Maybe instead of the color always being `#000` we set the color based on the color of the console?

**Comment by blackxored** [comment]
Is there a way to detect we're running on dark theme with Chrome APIs?

**Comment by romarioraffington** [comment]
@blackxored, in fact we can take another approach, similar to [redux-logger](https://github.com/evgenyrodionov/redux-logger).  See  example [here](https://github.com/evgenyrodionov/redux-logger/blob/c8b497189b1574b318a85c449b97f1a57e794465/src/defaults.js#L13).


Instead of setting the color for the `operationName` to `#000`, https://github.com/blackxored/apollo-link-logger/blob/ae825a5d275e0adebbf5b0545534c0448b814286/src/formatMessage.js#L5 we can use `inherit` and it will adjust the color based on the current Chrome theme.
