### ISSUE TITLE
What does the time metric mean for subscriptions?

### ISSUE THREAD

**Issue by tim-soft** [blackxored/apollo-link-logger#7]
Problem description: 
The reported latency for a simple subscription is coming in at 116 seconds -- what does that value mean?

Also, could the subscription text color be something different than mutation's red? Maybe a green color for subscriptions? 

This line would need to be broken out a little more for three diff colors:
https://github.com/blackxored/apollo-link-logger/blob/ae825a5d275e0adebbf5b0545534c0448b814286/src/formatMessage.js#L4

System:
* `apollo-link-logger` version: 1.2.0
* `node` version: 9.4.0
* `npm` (or `yarn`) version: yarn 1.3.2

Relevant code or config

```javascript
// Combine all links
const link = split(
  // split based on operation type: subscription or query/mutation
  ({ query }) => {
    const { kind, operation } = getMainDefinition(query);
    return kind === 'OperationDefinition' && operation === 'subscription';
  },

  // Subscriptions Link
  from([
    // Log Apollo operations in development
    ...(__DEV__ ? [apolloLogger] : []),

    // Handle subscriptions, log errors in dev
    ...(__DEV__ ? [errorLink.concat(subscriptionsLink)] : [subscriptionsLink]),
  ]),


  // Uploads/http Link
  from([
    // Log Apollo operations in development
    ...(__DEV__ ? [apolloLogger] : []),

    // Handle http/file uploads, include error logging in development
    ...(__DEV__ ? [errorLink.concat(uploadLink)] : [uploadLink]),
  ]),
);
```

What happened:

![capture](https://user-images.githubusercontent.com/10257939/35127146-ee6b48a0-fc6d-11e7-9e00-4b3bd716fa1a.PNG)

**Comment by tim-soft** [comment]
If you are getting this time from up the apollo chain somewhere,then I'm sure it means _something_, possibly some combination of `keepAlive` ack and websocket frame age?

Here's what I could fit in a screenshot. What do you think about making subscription a diff color? When you have a lot of mutations/subscriptions going on, it's hard to differentiate.

![capture](https://user-images.githubusercontent.com/10257939/35170739-7a61ab14-fd1e-11e7-933e-9bfa6eb14115.PNG)

**Comment by blackxored** [comment]
I think I'll probably remove performance info from subscriptions.
